version: '3.8'

services:
  frontend:
    build: 
      context: ./scheduler-front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./scheduler-front/app:/app/app
    # command: npx next build && npx next start
    depends_on:
      - mongo

  backend:
    build: 
      context: ./scheduler-back
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    command: node server.js
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/test_db?authSource=admin
      - PORT=5000
    volumes:
      - /etc/letsencrypt/live/os3-378-22222.vs.sakura.ne.jp:/etc/letsencrypt/live/example.com
      # example.com にしておけばドメインがバレてもいいと思ってこうした。。。

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false